/****** Object:  Table [dbo].[ART_KOPF]    Script Date: 3/12/2021 10:03:56 AM ******/
SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DAAS_EXPORT](
	[DAAS_KEY1] [varchar](15) NOT NULL,
	[DAAS_KEY2] [varchar](15) NOT NULL,
	[DAAS_KEY3] [varchar](15) NOT NULL,
	[DAAS_KEY4] [varchar](15) NOT NULL,
	[DAAS_KEY5] [varchar](15) NOT NULL,
	[DAAS_SET_NAME][varchar](15) NOT NULL,
	[DAAS_MD5] [nvarchar](1000) NOT NULL,
	[DAAS_UPDATE_TIME] [bigint] NOT NULL,
 CONSTRAINT [PK_DAAS_EXPORT] PRIMARY KEY CLUSTERED 
(
	[DAAS_KEY1] ASC,
	[DAAS_KEY2] ASC,
	[DAAS_KEY3] ASC,
	[DAAS_KEY4] ASC,
	[DAAS_KEY5] ASC,
	[DAAS_SET_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO